name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      contents: read
      id-token: write
    outputs:
      isUpload: ${{ steps.set.outputs.isUpload}}
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      
      - name: filter folder changes
        id: changes
        uses: dorny/paths-filter@v2
        with:
          token: ${{secrets.MY_GITHUB_TOKEN}}
          filters: |
            docs: 
              - "docs/**"
      
      - name: install yarn
        if: steps.changes.outputs.docs == 'true'
        run: yarn install
      
      - name: run tests
        if: steps.changes.outputs.docs == 'true'
        run: yarn run test
      
      - name: upload to github pages
        id: upload
        if: steps.changes.outputs.docs == 'true'
        uses: actions/upload-pages-artifact@v1
        with:
          path: docs
      - name: setIsUpload
        if: steps.changes.outputs.docs == 'true'
        id: set
        run: echo "isUpload=true" >> $GITHUB_OUTPUT

  deploy:
    needs: build
    permissions:
       pages: write
       id-token: write
    environment:
       name: github-pages
       url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
       - run: echo ${{needs.build.outputs.isUpload}}
       - name: Deploy to GitHub Pages
         if: ${{needs.build.outputs.isUpload}}=='true'
         id: deployment
         uses: actions/deploy-pages@v1
