name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      
      - name: filter folder changes
        id: filter
        uses: actions/filter@v2.1.0
        with:
          token: ${{secrets.MY_GITHUB_TOKEN}}
          filters: |
            path: 
              - "docs/**"
      
      - name: install yarn
        run: yarn install
      
      - name: run tests
        run: yarn run test
      
      - name: deploy to github pages
        uses: actions/upload-pages-artifact@v1
        with:
          path: "docs"
