name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      contents: read
      id-token: write
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      
      - name: filter folder changes
        id: changes
        uses: dorny/paths-filter@v2
        with:
          token: ${{secrets.MY_GITHUB_TOKEN}}
          filters: |
            docs: 
              - "docs/**"
      
      - name: install yarn
        run: yarn install
      
      - name: run tests
        run: yarn run test
      
      - name: upload to github pages
        id: upload
        if: steps.changes.outputs.docs == 'true'
        uses: actions/upload-pages-artifact@v1
        with:
          path: docs

  deploy:
    needs: build
    permissions:
       pages: write
       id-token: write
    environment:
       name: github-pages
       url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: filter folder changes
        id: changes
        uses: dorny/paths-filter@v2
        with:
          token: ${{secrets.MY_GITHUB_TOKEN}}
          filters: |
            docs: 
              - "docs/**"
      - name: Deploy to GitHub Pages
        if: steps.changes.outputs.docs == 'true'
        id: deployment
        uses: actions/deploy-pages@v1
