name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      
      - name: filter folder changes
        id: changes
        uses: dorny/paths-filter@v2
        with:
          token: ${{secrets.MY_GITHUB_TOKEN}}
          filters: |
            docs: 
              - "docs/**"
      
      
      
      - name: install yarn
        if: steps.changes.outputs.docs == 'true'
        run: yarn install
      
      - name: run tests
        if: steps.changes.outputs.docs == 'true'
        run: yarn run test
      
      - name: deploy to github pages
        if: steps.changes.outputs.docs == 'true'
        uses: actions/upload-pages-artifact@v1
        with:
          path: "docs"
